### ISSUE TITLE
Error "Task was destroyed but it is pending" when attempting to send a message after a few seconds the command was run

### ISSUE THREAD

**Issue by flamergamer1234** [Hexexpeck/Hex-Cogs#3]

**Comment by Hexexpeck** [comment]
Which specific cog is this referring to? If you don't know, this happened after you installed which cog?

**Comment by flamergamer1234** [comment]
Im referring to the one in which you can chat from the console

**Comment by Hexexpeck** [comment]
Yeah, I already knew about this issue and have a fix planned.

**Comment by CrunchyNapkin22** [comment]
nice to hear that this will get fixed, good job man...keep up the good work :D

**Comment by Hexexpeck** [comment]
This should be fixed with #4
